# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=9)),
                ('pages', models.IntegerField(default=0)),
                ('languages', models.CharField(max_length=32)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=60)),
            ],
        ),
    ]
