# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(default='password', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
