# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:11
from __future__ import unicode_literals

from django.db import migrations, connection
import os

def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), '../sql/', filename)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)

order_create = lambda x,y: load_data_from_sql('order_create.sql')

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171209_1906'),
    ]

    operations = [
    	migrations.RunPython(order_create),
    ]
