# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_pw'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
