# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:15
from __future__ import unicode_literals

from django.db import migrations, connection
import os

def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), '../sql/', filename)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)

trigger_order = lambda x,y: load_data_from_sql('trigger.sql')
order_data = lambda x,y: load_data_from_sql('order.sql')

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171209_1755'),
    ]

    operations = [
    	migrations.RunPython(trigger_order),
    	migrations.RunPython(order_data),
    ]
