# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171204_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='languages',
            new_name='language',
        ),
    ]
