# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20171204_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='languages',
        ),
    ]
