# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20171204_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
