CREATE TABLE myapp_orders(
loginName VARCHAR(64),
ISBN13 CHAR(14),
quantityOrdered INT NOT NULL,  # QUANTITY ORDERED MUST BE SMALLER OR EQUAL TO QUANTITY AVAILABLE
orderDate DATETIME NOT NULL,
PRIMARY KEY (loginName, ISBN13),
FOREIGN KEY (loginName) REFERENCES auth_user(username) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ISBN13) REFERENCES myapp_book(ISBN13) ON DELETE CASCADE ON UPDATE CASCADE)