INSERT INTO myapp_user (name, login, password, is_superuser, is_staff, is_active) VALUES
('XIE XIN', 'xiexin2011@gmail.com', '1TJT599QE2', FALSE, FALSE, TRUE),
('HUANG RAN', 'huangran1991@yahoo.com', 'CV3MVFY68O', FALSE, FALSE, TRUE),
('GOH ENG CHYE', 'gohengchye1992@msn.com', 'USRVX0A2M7', FALSE, FALSE, TRUE),
('GOH HUI YING', 'gohhuiying1989@gmail.com', 'FWTNTZ79NI', FALSE, FALSE, TRUE),
('FANG HAN', 'fanghan2011@hotmail.com', 'DFHQJYXGBF', FALSE, FALSE, TRUE),
('DING KUAN CHONG', 'dingkuanchong2010@msn.com', 'J9GL6SHTK9', FALSE, FALSE, TRUE),
('TAY WEI GUO', 'tayweiguo1989@msn.com', '6B2LA7YXLE', FALSE, FALSE, TRUE),
('ONG KAH HONG', 'ongkahhong1991@gmail.com', '0WGOM6AOBF', FALSE, FALSE, TRUE),
('PENG JIAYUAN', 'pengjiayuan2011@hotmail.com', 'WSZE68YG1F', FALSE, FALSE, TRUE),
('HUANG ZHANPENG', 'huangzhanpeng1992@msn.com', 'LJ9II5LYLR', FALSE, FALSE, TRUE),
('NGOO GEK PING', 'ngoogekping1990@hotmail.com', 'A3M218KZU2', FALSE, FALSE, TRUE),
('GE YUWEI', 'geyuwei1992@hotmail.com', 'OTSW1M6XC0', FALSE, FALSE, TRUE),
('ZHENG ZHEMIN', 'zhengzhemin1991@yahoo.com', 'RRVRSIB9JD', FALSE, FALSE, TRUE),
('LIU ZHANPENG', 'liuzhanpeng2011@msn.com', 'TS4KRHNH0X', FALSE, FALSE, TRUE),
('HUANG WENXIN', 'huangwenxin2010@msn.com', '4GT46RXG9T', FALSE, FALSE, TRUE),
('CHOY WEI XIANG', 'choyweixiang2011@gmail.com', '00MLK7ZHDU', FALSE, FALSE, TRUE),
('WANG NA', 'wangna1990@yahoo.com', '61LBQNVOJM', FALSE, FALSE, TRUE),
('ZHOU HUICHAN', 'zhouhuichan1990@msn.com', 'A2SNIMH15U', FALSE, FALSE, TRUE),
('NG ANH QUANG', 'nganhquang1991@yahoo.com', '5Q4JYG2TXH', FALSE, FALSE, TRUE),
('HUANG QI', 'huangqi1990@msn.com', 'IM1CNEV20N', FALSE, FALSE, TRUE),
('DING GEK PING', 'dinggekping1991@msn.com', 'ID5H4HD5AT', FALSE, FALSE, TRUE),
('POH HUI LING', 'pohhuiling1992@hotmail.com', 'DNDN02L107', FALSE, FALSE, TRUE),
('NG QI YANG', 'ngqiyang1989@msn.com', 'GC97YEFLHJ', FALSE, FALSE, TRUE),
('NEELAM DEOL', 'neelamdeol2011@hotmail.com', 'FTOGQNGWG5', FALSE, FALSE, TRUE),
('LI YUZHAO', 'liyuzhao1990@gmail.com', '6AHZMPH0OJ', FALSE, FALSE, TRUE),
('VARGHESE ANEJA', 'vargheseaneja1992@msn.com', '6VLXNPMFFG', FALSE, FALSE, TRUE),
('LIU SHAOJUN', 'liushaojun2010@msn.com', 'GA2I114P81', FALSE, FALSE, TRUE),
('QIN YIYANG', 'qinyiyang2010@hotmail.com', 'XQCCUGEM8F', FALSE, FALSE, TRUE),
('ZHOU CONG', 'zhoucong1990@yahoo.com', 'J9JKZ5YJVN', FALSE, FALSE, TRUE),
('TAY YONG MING', 'tayyongming1989@gmail.com', 'ETL4YV46S7', FALSE, FALSE, TRUE),
('SIOW CAO KHOA', 'siowcaokhoa1991@msn.com', 'Y9MY702SN5', FALSE, FALSE, TRUE),
('NI HANRAN', 'nihanran1989@msn.com', '32FGMX9Q1L', FALSE, FALSE, TRUE),
('CHOY YI TING', 'choyyiting1992@hotmail.com', 'O0KAZMDFSI', FALSE, FALSE, TRUE),
('DENNIS BECKHAM', 'dennisbeckham1989@msn.com', '8T3UTWKMVZ', FALSE, FALSE, TRUE),
('ZHANG ZHUO', 'zhangzhuo1989@hotmail.com', '98HR8ZSJH0', FALSE, FALSE, TRUE),
('ANUPAMA ANGHAN', 'anupamaanghan2010@yahoo.com', 'X3ZXEQ9WZ5', FALSE, FALSE, TRUE),
('LIU QIAN', 'liuqian1991@yahoo.com', 'OKLITSW12O', FALSE, FALSE, TRUE),
('ZHANG YINGBO', 'zhangyingbo1989@msn.com', 'O3BYC796R7', FALSE, FALSE, TRUE),
('CHIA YEU ARNG', 'chiayeuarng1991@hotmail.com', 'XSVT14JR19', FALSE, FALSE, TRUE),
('ZENG YIHUI', 'zengyihui2010@yahoo.com', 'TBVTNETGOV', FALSE, FALSE, TRUE),
('FENG MENG', 'fengmeng1990@gmail.com', 'GRVLNF4GET', FALSE, FALSE, TRUE),
('ZHANG HAN', 'zhanghan1989@hotmail.com', '9OPT3S6VXD', FALSE, FALSE, TRUE),
('LIU DANNI', 'liudanni1991@yahoo.com', 'S9LLJKHM8S', FALSE, FALSE, TRUE),
('SOH JIE FENG', 'sohjiefeng1991@msn.com', 'HXZXHM3D5Y', FALSE, FALSE, TRUE),
('TAN CHENG HAN', 'tanchenghan1990@msn.com', '1G4FPR2O2Y', FALSE, FALSE, TRUE),
('JENNY HUNT', 'jennyhunt1991@gmail.com', 'Q33V5UJVH7', FALSE, FALSE, TRUE),
('DING YANG', 'dingyang1989@gmail.com', 'EYEF84U0O2', FALSE, FALSE, TRUE),
('ZHANG HONG', 'zhanghong2011@msn.com', 'SFXHR9I6YN', FALSE, FALSE, TRUE),
('XU HUAJUN', 'xuhuajun1990@msn.com', '9337PL6DNV', FALSE, FALSE, TRUE),
('SOMESH ANEJA', 'someshaneja2011@yahoo.com', 'EE23MQIFTP', FALSE, FALSE, TRUE),
('SEAH TECK KEE', 'seahteckkee1990@gmail.com', '6NEB1KAQC4', FALSE, FALSE, TRUE),
('LIU YIHUI', 'liuyihui1990@hotmail.com', 'G44QMSHG3Z', FALSE, FALSE, TRUE),
('ZHU CHANG', 'zhuchang2010@gmail.com', 'HGZAB0GDTL', FALSE, FALSE, TRUE),
('ZHENG XI', 'zhengxi1990@yahoo.com', 'MKO8NM3M9N', FALSE, FALSE, TRUE),
('YEO JIA HAO', 'yeojiahao1989@yahoo.com', 'H7KPRGVD9K', FALSE, FALSE, TRUE),
('ANNIE CHAPMAN', 'anniechapman1991@yahoo.com', '8C91FFJVMH', FALSE, FALSE, TRUE),
('JERRY BROWN', 'jerrybrown2010@gmail.com', 'Z21MCKDRGZ', FALSE, FALSE, TRUE),
('ZHOU XIALIN', 'zhouxialin1990@yahoo.com', 'CUTENOSVSB', FALSE, FALSE, TRUE),
('TAN HUI LIN', 'tanhuilin1989@hotmail.com', 'AGTABAQA7O', FALSE, FALSE, TRUE),
('JENNY BECKHAM', 'jennybeckham1992@gmail.com', 'UDKPQUU51M', FALSE, FALSE, TRUE),
('HENRY HUNT', 'henryhunt1992@yahoo.com', 'AP44CWKV9H', FALSE, FALSE, TRUE),
('LIU JUN', 'liujun1992@msn.com', 'EKOFVIGF7O', FALSE, FALSE, TRUE),
('ZHANG ZHANPENG', 'zhangzhanpeng1992@hotmail.com', '4FVQ5SSW5A', FALSE, FALSE, TRUE),
('DAVID CHAPMAN', 'davidchapman1989@msn.com', 'UFWSM2I2HD', FALSE, FALSE, TRUE),
('QIN YUWEI', 'qinyuwei2011@hotmail.com', 'KVWJNZFR0H', FALSE, FALSE, TRUE),
('DENNIS PALMER', 'dennispalmer1992@yahoo.com', 'RPPY55MX0M', FALSE, FALSE, TRUE),
('KRUPESH ANDHAK', 'krupeshandhak1991@yahoo.com', 'R0UHB8XM0Z', FALSE, FALSE, TRUE),
('LEE YI JIA', 'leeyijia1989@gmail.com', 'UXKF81IWDB', FALSE, FALSE, TRUE),
('DAVID HALL', 'davidhall1992@yahoo.com', 'M7FKT0H5N1', FALSE, FALSE, TRUE),
('SEAH WENG FAI', 'seahwengfai1990@yahoo.com', 'JY5P9T5JZ0', FALSE, FALSE, TRUE),
('SHEN TIANYI', 'shentianyi1991@msn.com', 'I8I5PHV2MH', FALSE, FALSE, TRUE),
('WEN NA', 'wenna1990@msn.com', '3X5JDFMR4Q', FALSE, FALSE, TRUE),
('LIU LINXI', 'liulinxi1991@yahoo.com', 'MFCJ0V1LM4', FALSE, FALSE, TRUE),
('DING WEI XIANG', 'dingweixiang1990@yahoo.com', 'PTVQUOTI0D', FALSE, FALSE, TRUE),
('CHEW SOEN NAM', 'chewsoennam1989@msn.com', 'GPOOHEZWKO', FALSE, FALSE, TRUE),
('IRIS BROWN', 'irisbrown1992@hotmail.com', '0BQZXKZ0SN', FALSE, FALSE, TRUE),
('KEN OWEN', 'kenowen2011@yahoo.com', 'Q9IIC4U9FD', FALSE, FALSE, TRUE),
('ZHANG YUZHAO', 'zhangyuzhao1990@gmail.com', 'GWLUV964G3', FALSE, FALSE, TRUE),
('GE DUO', 'geduo2010@yahoo.com', 'HP1VJTS0AG', FALSE, FALSE, TRUE),
('HUANG XUANTI', 'huangxuanti1992@msn.com', 'F26V0B2CSL', FALSE, FALSE, TRUE),
('LISA SMITH', 'lisasmith2011@msn.com', 'RK0RUDAI4P', FALSE, FALSE, TRUE),
('CHOY JIAN MIN', 'choyjianmin1991@gmail.com', 'VALG7VDRVE', FALSE, FALSE, TRUE),
('NG YONG MING', 'ngyongming2011@yahoo.com', 'JZJYQNVUUA', FALSE, FALSE, TRUE),
('ZHENG NANA', 'zhengnana1991@gmail.com', '5BGBM4LJAI', FALSE, FALSE, TRUE),
('ZHAO YANG', 'zhaoyang1989@yahoo.com', '9TC0YYUPH2', FALSE, FALSE, TRUE),
('NEHAL KANWAT', 'nehalkanwat1989@gmail.com', 'S8RPZASEYW', FALSE, FALSE, TRUE),
('NG YAN FEN', 'ngyanfen2010@msn.com', 'XH7YAVE2E4', FALSE, FALSE, TRUE),
('ANG JIA YI', 'angjiayi1990@hotmail.com', 'Y7ZKDZDPM6', FALSE, FALSE, TRUE),
('CHNG HUI LING', 'chnghuiling1992@gmail.com', 'EUTQHCYQ15', FALSE, FALSE, TRUE),
('TAN WEI SHENG', 'tanweisheng1989@gmail.com', '06WKBECG32', FALSE, FALSE, TRUE),
('LIEW LIEN LER', 'liewlienler2010@yahoo.com', '285IIF5S0D', FALSE, FALSE, TRUE),
('NGOO KAI TING', 'ngookaiting1991@yahoo.com', 'MPWAXKQ2SX', FALSE, FALSE, TRUE),
('LIU JUN', 'liujun1989@msn.com', 'ZIPFQ4XMIM', FALSE, FALSE, TRUE),
('SHEN WANTING', 'shenwanting2011@yahoo.com', 'GLJ1SLMHZR', FALSE, FALSE, TRUE),
('ZHANG CONG', 'zhangcong2010@hotmail.com', '6EWQGSHQO2', FALSE, FALSE, TRUE),
('SUBRAMANIAM GHANTASALA', 'subramaniamghantasala2011@msn.com', 'VITD02AVAO', FALSE, FALSE, TRUE),
('TSO HUI LIN', 'tsohuilin1989@msn.com', 'I5HRZ0CMWY', FALSE, FALSE, TRUE),
('CHIA WEI GUO', 'chiaweiguo1990@hotmail.com', 'BU031QI15W', FALSE, FALSE, TRUE),
('LIU YIYANG', 'liuyiyang1992@msn.com', '025Q0QAYFU', FALSE, FALSE, TRUE),
('LIU ZHENCAI', 'liuzhencai1990@msn.com', '62SFR3MRI3', FALSE, FALSE, TRUE)